#include <stdio.h>
#include <stdlib.h>
#include "Util/symbol_table.h"
#include "Util/statements_list.h"
#include "Step2/code_generator.h"

/* ===========================================================
 * Declared in lex.yy.c (generated by Flex) 
 * ============================================================ */

 void init_lexer(const char *filename);
int  yylex_destroy(void);
extern FILE *yyin;

/* ===========================================================
 * Declared in parser.y (generated by Bison) 
 * ============================================================ */

int yyparse(void);

/* ===========================================================
 * Assembler driver: initializes data structures and runs 
 * ============================================================ */

int main(int argc, char *argv[])
{
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <source.asm>\n", argv[0]);
        return EXIT_FAILURE;
    }

    // -- 1. Initialize symbol table, statements list, and lexer
    init_symbol_table();
    init_statements_list();
    init_lexer(argv[1]);

    if (yyparse() != 0) {
        fprintf(stderr, "Parse error — aborting.\n");
        return EXIT_FAILURE;
    }

    // -- 2. Generate code from the statement list
    int rc = generate_code();

    // -- 3. Clean up resources
    delete_statements_list();
    delete_symbol_table();
    fclose(yyin);
    yylex_destroy();

    return rc == 0 ? EXIT_SUCCESS : EXIT_FAILURE;
}
