#ifndef PARSER_TAB_H
#define PARSER_TAB_H

typedef union {
    int    ival;
    double fval;
    char   cval;
    char*  sval;
} YYSTYPE;

extern YYSTYPE yylval;  

typedef enum {
    TOKEN_NUM = 258, TOKEN_FNUM, TOKEN_CNUM, TOKEN_STR, TOKEN_ID,
    TOKEN_INT, TOKEN_CHAR, TOKEN_FLOAT, TOKEN_DOUBLE, TOKEN_VOID,
    TOKEN_INLINE, TOKEN_SIGNED, TOKEN_UNSIGNED, TOKEN_LONG, TOKEN_SHORT,
    TOKEN_STATIC, TOKEN_EXTERN, TOKEN_CONST, TOKEN_VOLATILE,
    TOKEN_IF, TOKEN_ELSE, TOKEN_SWITCH, TOKEN_CASE, TOKEN_DEFAULT,
    TOKEN_FOR, TOKEN_WHILE, TOKEN_DO, TOKEN_BREAK, TOKEN_CONTINUE,
    TOKEN_RETURN, TOKEN_GOTO,
    TOKEN_LEFT_SHIFT_ASSIGN, TOKEN_RIGHT_SHIFT_ASSIGN,
    TOKEN_PLUS_ASSIGN, TOKEN_MINUS_ASSIGN, TOKEN_MULTIPLY_ASSIGN,
    TOKEN_DIVIDE_ASSIGN, TOKEN_MODULUS_ASSIGN,
    TOKEN_AND_ASSIGN, TOKEN_OR_ASSIGN, TOKEN_XOR_ASSIGN,
    TOKEN_INCREMENT, TOKEN_DECREMENT,
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_ASTERISK, TOKEN_OVER, TOKEN_PERCENT,
    TOKEN_EQUAL, TOKEN_NOT_EQUAL,
    TOKEN_LESS_THAN_OR_EQUAL, TOKEN_GREATER_THAN_OR_EQUAL,
    TOKEN_LESS_THAN, TOKEN_GREATER_THAN,
    TOKEN_LOGICAL_AND, TOKEN_LOGICAL_OR, TOKEN_LOGICAL_NOT,
    TOKEN_LEFT_SHIFT, TOKEN_RIGHT_SHIFT,
    TOKEN_BITWISE_AND, TOKEN_BITWISE_OR, TOKEN_BITWISE_XOR, TOKEN_BITWISE_NOT,
    TOKEN_ASSIGN,
    TOKEN_SEMI, TOKEN_COMMA, TOKEN_COLON, TOKEN_TERNARY,
    TOKEN_LEFT_PARENTHESES, TOKEN_RIGHT_PARENTHESES,
    TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET,
    TOKEN_ERROR
} TokenType;

#endif
